### PR TITLE
Add MergeCommandBuilder, add merge to GitRepository

### PR DESCRIPTION
**Pull request by Arkitecht**
Rebased on develop and added merge

### CODE REVIEW

**Comment by tristanlins** [comment]
Please fix the codestyle violations, see https://travis-ci.org/bit3/git-php/jobs/79207825#L329-L388
When travis success, I'll merge it gladly. :-)

**Comment by Arkitecht** [comment]
I am working on the fixes. Any suggestions on how I can test the build with Travis CI locally before pushing updates to the repo (so we don't have bunch of extra commits)? I am somewhat new to this process.

**Comment by tristanlins** [comment]
You can run `ant -keep-going` locally, see https://github.com/bit3/git-php/blob/master/.travis.yml#L15

**Comment by Arkitecht** [comment]
Thanks, that was a big help. All set!

**Comment by tristanlins** [comment]
Thank you very much, I released a new version 1.2.0 which contains the new merge command :-)

**Pull request merged**
