### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Arkitecht**
Added merge support

### CODE REVIEW

**Comment by discordier** [comment]
Could you rebase your repository to current master?

Second, there are a lot of options missing if I compare the man page with your implementation. This is however not a big problem IMO. @tristanlins what do you think?

**Comment by tristanlins** [comment]
Yes there are a lot more options, but I'm absolutely fine with this. But please rebase against develop, not master! We use git flow for this repository.

**Comment by discordier** [comment]
@Arkitecht Any chance that you will rebase this PR anytime soon?

**Comment by Arkitecht** [comment]
Sorry, this can be closed. Rebased and re-submitted (and the changes were merged in) in a separate pull request: https://github.com/bit3/git-php/pull/3

**Comment by discordier** [comment]
Ah, sorry, forgot about that one. Thanks.

**Pull request closed without merging**
